name: Deploy S3 bucket

on:
  push:
    branches:
      - 4.testes

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        python -m pip install --upgrade pip
        cd turma_2/2_integracao_continua_e_testes/4.testes
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd turma_2/2_integracao_continua_e_testes/4.testes
        python -m pytest tests/unit

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        cd turma_2/2_integracao_continua_e_testes/4.testes
        cdk synth
        cdk deploy

    - name: Run integration tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        cd turma_2/2_integracao_continua_e_testes/4.testes/
        python -m pytest tests/integration